# Configuration for welcome - https://github.com/behaviorbot/welcome

#
# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome
#
# Comment to be posted to on first time issues
newIssueWelcomeComment: >
   📢 Nice one! Your first issue! Thanks for telling us how to improve `geovista` 📢


#
# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome
#
# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  🚀 Awesome! Your first pull request! Thanks for contributing to `geovista`! 🚀


#
# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge
#
# Comment to be posted on pull requests merged by a first time user
firstPRMergeComment: >
  🤟 Congrats on merging your first pull request! Let the good times roll! 🤟
