'type: dependencies':
  - requirements/geovista.yml
  - requirements/pypi*.txt
  - requirements/locks/py*.txt
'type: documentation':
  - docs/**/*
'type: examples':
  - src/geovista/examples/**/*
'type: gha':
  - .github/*.yml
  - .github/**/*.yml
'type: infrastructure':
  - '*'
'type: testing':
  - tests/**/*
