#!/usr/bin/env python3
# Copyright (c) 2021, GeoVista Contributors.
#
# This file is part of GeoVista and is distributed under the 3-Clause BSD license.
# See the LICENSE file in the package root directory for licensing details.

"""Refresh the vendored intersphinx fallback inventories.

Each inventory under "docs/src/_inventory" is the local fallback for the
matching entry in the "intersphinx_mapping" of "docs/src/conf.py", consulted
only when the remote inventory cannot be reached. The mapping is the single
source of truth; this script reads it rather than repeating it.

An "objects.inv" is zlib compressed and regenerated by every upstream
documentation build, so its bytes differ almost daily while the targets it
carries do not. Comparing the decompressed payload instead keeps a monthly
refresh to the inventories that have genuinely moved, rather than rewriting
all of them every time.

Notes
-----
.. versionadded:: 0.6.0

"""

from __future__ import annotations

import ast
import os
from pathlib import Path
import posixpath
import sys
import time
import urllib.error
import urllib.request
import zlib

#: The sphinx configuration carrying the intersphinx mapping.
CONF = Path(__file__).parents[2] / "docs" / "src" / "conf.py"

#: The filename of an inventory, as served by a sphinx site.
FILENAME = "objects.inv"

#: The number of plain text header lines preceding the compressed payload of
#: a version 2 inventory.
HEADER = 4

#: The header declaring the only inventory format that sphinx loads, and the
#: compression it declares. A payload which decompresses is not necessarily
#: one sphinx will accept, and an inventory it rejects is no fallback at all.
VERSION = b"# Sphinx inventory version 2"
COMPRESSION = b"zlib"

#: The schemes an inventory may be fetched over.
SCHEMES = ("https://", "http://")

#: The number of attempts made to fetch an inventory.
ATTEMPTS = 3

#: Seconds to wait for an inventory, and the delay between attempts.
TIMEOUT = 30
BACKOFF = 5

#: Identifies the fetcher to the upstream site, some of which refuse the
#: default urllib agent.
AGENT = "geovista-inventories (+https://github.com/bjlittle/geovista)"

GITHUB_STEP_SUMMARY = os.getenv("GITHUB_STEP_SUMMARY")


def mapping(conf: Path) -> tuple[dict[str, str], str]:
    """Read the intersphinx mapping out of the sphinx configuration.

    The configuration is parsed rather than imported, as importing it requires
    the entire documentation environment.

    Parameters
    ----------
    conf : Path
        The sphinx configuration file.

    Returns
    -------
    tuple of dict and str
        The documentation set URLs, keyed by name, and the directory of the
        vendored inventories relative to the configuration.

    Raises
    ------
    RuntimeError
        When the configuration carries neither name.

    Notes
    -----
    .. versionadded:: 0.6.0

    """
    wanted = {"INTERSPHINX_URLS", "INVENTORY_DIR"}
    found: dict[str, object] = {}

    for node in ast.parse(conf.read_text(encoding="utf-8"), filename=str(conf)).body:
        if not isinstance(node, ast.Assign):
            continue

        for target in node.targets:
            if isinstance(target, ast.Name) and target.id in wanted:
                found[target.id] = ast.literal_eval(node.value)

    if missing := sorted(wanted - set(found)):
        emsg = f"no {', '.join(missing)} found in {conf}"
        raise RuntimeError(emsg)

    urls: dict[str, str] = found["INTERSPHINX_URLS"]  # type: ignore[assignment]
    directory: str = found["INVENTORY_DIR"]  # type: ignore[assignment]

    return urls, directory


def payload(raw: bytes) -> bytes:
    """Decompress the body of an inventory, rejecting one sphinx cannot load.

    The header is checked as well as the payload. A file whose body
    decompresses is not thereby readable - sphinx refuses an unexpected
    version or compression outright - and accepting one would vendor a
    fallback that fails on the very day it is wanted.

    Parameters
    ----------
    raw : bytes
        The contents of an inventory.

    Returns
    -------
    bytes
        The targets it carries, free of compression noise.

    Raises
    ------
    ValueError
        When the inventory is not in the version 2 format.

    Notes
    -----
    .. versionadded:: 0.6.0

    """
    lines = raw.split(b"\n", HEADER)

    if len(lines) <= HEADER:
        emsg = f"expected {HEADER} header lines, got {len(lines) - 1}"
        raise ValueError(emsg)

    # sphinx compares the version line only once stripped of trailing space
    if (version := lines[0].rstrip()) != VERSION:
        found = version.decode(errors="replace")
        emsg = f"expected {VERSION.decode()!r}, got {found!r}"
        raise ValueError(emsg)

    if COMPRESSION not in (declared := lines[HEADER - 1]):
        found = declared.decode(errors="replace")
        emsg = (
            f"expected a payload compressed with {COMPRESSION.decode()}, got {found!r}"
        )
        raise ValueError(emsg)

    return zlib.decompress(lines[HEADER])


def fetch(url: str) -> bytes:
    """Download an inventory, retrying a failure.

    Parameters
    ----------
    url : str
        The location of the inventory.

    Returns
    -------
    bytes
        The contents of the inventory.

    Raises
    ------
    ValueError
        When the location is not fetchable over a permitted scheme.
    URLError
        When every attempt fails.

    Notes
    -----
    .. versionadded:: 0.6.0

    """
    if not url.startswith(SCHEMES):
        emsg = f"refusing to fetch {url!r}, expected one of {SCHEMES}"
        raise ValueError(emsg)

    request = urllib.request.Request(url, headers={"User-Agent": AGENT})  # noqa: S310

    for attempt in range(1, ATTEMPTS + 1):
        try:
            with urllib.request.urlopen(request, timeout=TIMEOUT) as response:  # noqa: S310
                return bytes(response.read())
        except (urllib.error.URLError, TimeoutError, OSError):
            if attempt == ATTEMPTS:
                raise

            time.sleep(BACKOFF * attempt)

    emsg = "unreachable"
    raise RuntimeError(emsg)


def refresh(url: str, inventory: Path) -> str:
    """Bring a single vendored inventory up to date.

    Parameters
    ----------
    url : str
        The base URL of the documentation set.
    inventory : Path
        The vendored inventory of the documentation set.

    Returns
    -------
    str
        What became of it.

    Notes
    -----
    .. versionadded:: 0.6.0

    """
    try:
        raw = fetch(posixpath.join(url, FILENAME))
        fresh = payload(raw)
    except Exception as err:  # noqa: BLE001
        return f"⚠️ failed - {err}"

    if inventory.is_file():
        try:
            if payload(inventory.read_bytes()) == fresh:
                return "unchanged"
        except (ValueError, zlib.error):
            # an inventory that cannot be read is replaced rather than compared,
            # as a corrupt header alone leaves the payload matching the remote
            pass

        action = "updated"
    else:
        action = "added"

    inventory.parent.mkdir(parents=True, exist_ok=True)
    inventory.write_bytes(raw)

    return f"**{action}** - {len(fresh.splitlines())} targets"


def main() -> int:
    """Refresh every vendored inventory.

    Returns
    -------
    int
        Zero unless no inventory at all could be fetched.

    Notes
    -----
    .. versionadded:: 0.6.0

    """
    urls, directory = mapping(CONF)
    results = {
        name: refresh(url, CONF.parent / directory / f"{name}.inv")
        for name, url in sorted(urls.items())
    }

    table = [
        "| Inventory | Status |",
        "| --- | --- |",
        *(f"| `{name}` | {result} |" for name, result in results.items()),
    ]
    failed = [name for name, result in results.items() if result.startswith("⚠️")]

    # stdout is the body of the pull-request raised by "ci-inventories.yml"
    print("\n".join(table))

    if GITHUB_STEP_SUMMARY:
        summary = ["### 📚 Intersphinx Inventories", "", *table]
        with Path(GITHUB_STEP_SUMMARY).open("a", encoding="utf-8") as stream:
            stream.write("\n".join(summary) + "\n")

    if len(failed) == len(results):
        print("\nno inventory could be fetched", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
