version: 2

build:
  os: ubuntu-22.04
  tools:
    python: mambaforge-22.9
  apt_packages:
    - libgl1-mesa-dev
    - xvfb
  jobs:
    post_checkout:
      - git fetch --unshallow
      - git fetch --all
    post_install:
      - geovista download --all --decompress

conda:
  environment: requirements/locks/rtd.yml

sphinx:
  configuration: docs/src/conf.py
  fail_on_warning: false

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - cmap
        - docs
