version: 2

build:
  os: ubuntu-22.04
  tools:
    python: mambaforge-23.11
  apt_packages:
    - libgl1-mesa-dev
    - xvfb
  jobs:
    post_checkout:
      # require full history for correct setuptools-scm version discovery
      - |
        git fetch --unshallow
        git fetch --all
        #
        # https://docs.readthedocs.com/platform/stable/build-customization.html#cancel-build-based-on-a-condition
        # https://docs.readthedocs.com/platform/stable/reference/environment-variables.html#envvar-READTHEDOCS_VERSION_TYPE
        #
        if [ "${READTHEDOCS_VERSION_TYPE}" = "external" ] && git diff --quiet origin/main -- .all-contributorsrc .readthedocs.yml CHANGELOG.rst pixi.lock pyproject.toml changelog/ requirements/;
        then
          # (sum(list("skip".encode("ascii"))) % 256) == 183
          exit 183;
        fi
    pre_install:
      # keep checkout untainted from RTD to ensure correct
      # setuptools-scm version
      - git stash
    post_install:
      - |
        git stash pop
        geovista download --operational --decompress

conda:
  environment: requirements/locks/rtd.yml

sphinx:
  configuration: docs/src/conf.py
  fail_on_warning: false

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
