version: 2

build:
  os: ubuntu-22.04
  tools:
    python: mambaforge-23.11
  apt_packages:
    - libgl1-mesa-dev
    - xvfb
  jobs:
    post_checkout:
      # require full history for correct setuptools-scm version discovery
      - git fetch --unshallow
      - git fetch --all
    pre_install:
      # keep checkout untainted from RTD to ensure correct
      # setuptools-scm version
      - git stash
    post_install:
      - git stash pop
      - geovista download --operational --decompress

conda:
  environment: requirements/locks/rtd.yml

sphinx:
  configuration: docs/src/conf.py
  fail_on_warning: false

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - cmap
        - docs
