coverage:
  # see https://docs.codecov.com/docs/commit-status
  status:
    project:
      default:
        target: auto
        threshold: 5%  # coverage can drop by up to <threshold>% while still posting success
    patch: off

ignore:
  - "**/cli.py"
  - "**/geoplotter.py"
  - "**/image_cache"
  - "**/pantry/data.py"
  - "**/pantry/meshes.py"
  - "**/cache/registry.txt"
  - "**/report.py"
