coverage:
  # see https://docs.codecov.com/docs/commit-status
  status:
    project:
      default:
        target: 20 
        threshold: 10%  # coverage can drop by up to <threshold>% while still posting success
    patch: off

ignore:
  - registry.txt
  - pantry.py
  - samples.py

