# Copyright (c) 2021, GeoVista Contributors.
#
# This file is part of GeoVista and is distributed under the 3-Clause BSD license.
# See the LICENSE file in the package root directory for licensing details.

"""Sphinx extension to estimate reading time for documentation pages.

The count is taken from the parsed doctree rather than from the page source,
so directive names, option lines, link targets and comments are not counted as
words a reader reads, and a body generated by another directive is. That is
why the work happens on ``doctree-read`` rather than in ``run()``: the
directive returns a placeholder, which the handler below fills in once the
document it is measuring exists.

The rate, the word pattern and the argument grammar live in :mod:`reading`,
which imports nothing beyond the standard library and so is covered by unit
tests wherever they run.

Notes
-----
.. versionadded:: 0.6.0

"""

from __future__ import annotations

from typing import TYPE_CHECKING

from docutils import nodes
import reading
from sphinx.util.docutils import SphinxDirective

if TYPE_CHECKING:
    from sphinx.application import Sphinx

__all__ = ["ReadingTimeDirective", "setup"]

#: Doctree text that a reader never reads.
SKIP: tuple[type[nodes.Element], ...] = (
    nodes.system_message,
    nodes.comment,
    nodes.raw,
)

#: The clock, as the markup pydata-sphinx-theme itself emits for a Font Awesome
#: glyph. Raw HTML rather than a CSS "::before" rule, which would have to name
#: the font family and would break silently on a theme upgrade.
ICON: str = '<i class="fa-solid fa-clock"></i>'


class readingtime(nodes.Element):  # noqa: N801
    """A placeholder standing where the banner goes until the page is parsed.

    Deliberately **not** registered with ``app.add_node``. Were the handler
    below ever to stop firing, sphinx reports an unknown node type, which
    ``--fail-on-warning`` turns into a build failure - whereas a registered
    node would quietly publish a blank space.

    Notes
    -----
    .. versionadded:: 0.6.0

    """


class ReadingTimeDirective(SphinxDirective):
    """Directive to estimate reading time for a documentation page.

    Notes
    -----
    .. versionadded:: 0.6.0

    """

    has_content = False
    optional_arguments = 1
    final_argument_whitespace = False

    def run(self) -> list[nodes.Node]:
        """Return the placeholder that the ``doctree-read`` handler resolves.

        Directive accepts a single optional argument which may be either the
        proposed reading-time i.e., do not calculate an estimate instead use
        the value provided e.g. "10". Alternatively, the number of words per
        minute (override ``WPM`` default) to be used for the estimation
        e.g., "100wpm".

        Returns
        -------
        list[nodes.Node]
            A list containing a single unresolved :class:`readingtime` element.

        Raises
        ------
        docutils.parsers.rst.DirectiveError
            When the argument matches neither documented shape.

        Notes
        -----
        .. versionadded:: 0.6.0

        """
        # the rendered banner depends on the rate and the word pattern of
        # "reading", and on the markup of this module, neither of which is a
        # document source that sphinx already watches - so without these an
        # incremental build serves a pickled doctree carrying a stale estimate
        self.env.note_dependency(reading.__file__)
        self.env.note_dependency(__file__)

        argument = self.arguments[0] if self.arguments else None

        try:
            parsed = reading.parse_argument(argument)
        except ValueError as err:
            raise self.error(str(err)) from err

        return [readingtime(minutes=parsed.minutes, wpm=parsed.wpm)]


def count_doctree_words(doctree: nodes.document) -> int:
    """Count the words a reader reads on the parsed page.

    Parameters
    ----------
    doctree : nodes.document
        The parsed document.

    Returns
    -------
    int
        The words in every text node not descended from :data:`SKIP`.

    Notes
    -----
    .. versionadded:: 0.6.0

    """
    total = 0

    for text in doctree.findall(nodes.Text):
        node = text.parent

        while node is not None and not isinstance(node, SKIP):
            node = node.parent

        if node is None:
            total += reading.count_words(text.astext())

    return total


def banner(minutes: int) -> nodes.container:
    """Build the banner for a page of `minutes` minutes.

    Parameters
    ----------
    minutes : int
        The estimate to publish.

    Returns
    -------
    nodes.container
        Real docutils nodes rather than a raw HTML block, which only the HTML
        builder would render, so that ``text``, ``man`` and ``latex`` carry the
        estimate too.

    Notes
    -----
    .. versionadded:: 0.6.0

    """
    paragraph = nodes.paragraph()
    paragraph += nodes.raw("", ICON, format="html")
    paragraph += nodes.Text(
        f"Estimated reading time: {minutes} minute{'s' if minutes != 1 else ''}"
    )

    container = nodes.container(classes=["reading-time"])
    container += paragraph

    return container


def resolve(app: Sphinx, doctree: nodes.document) -> None:  # noqa: ARG001
    """Replace each placeholder on this page with its banner.

    Parameters
    ----------
    app : Sphinx
        The Sphinx application object. Unread: the count is a property of the
        page alone.
    doctree : nodes.document
        The parsed document, counted once however many placeholders it carries.

    Notes
    -----
    .. versionadded:: 0.6.0

    """
    placeholders = list(doctree.findall(readingtime))

    if not placeholders:
        return

    words = count_doctree_words(doctree)

    for node in placeholders:
        minutes = node["minutes"]

        if minutes is None:
            minutes = reading.estimate_minutes(words, node["wpm"])

        node.replace_self(banner(minutes))


def setup(app: Sphinx) -> dict[str, object]:
    """Set up the reading time Sphinx extension.

    Parameters
    ----------
    app : Sphinx
        The Sphinx application object.

    Returns
    -------
    dict
        A dictionary containing the extension version.

    Notes
    -----
    .. versionadded:: 0.6.0

    """
    app.add_directive("readingtime", ReadingTimeDirective)
    app.connect("doctree-read", resolve)

    return {
        "version": "1.0",
        "parallel_read_safe": True,
        "parallel_write_safe": True,
    }
