name: "conda-env-cache"
description: "create and cache the conda environment"

#
# Assumes the environment contains the following variables:
#   - CONDA
#
inputs:
  cache_period:
    description: "conda environment cache timestamp"
    required: true
  env_name:
    description: "gha environment name"
    required: true
  install_packages:
    description: "conda packages to install into environment"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/cache@v4
      id: conda-env-cache
      with:
        path: ${{ env.CONDA }}/envs/${{ inputs.env_name }}
        key: ${{ runner.os }}-conda-env-${{ inputs.env_name }}-${{ inputs.cache_period }}

    - if: steps.conda-env-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        conda install --quiet --name ${{ inputs.env_name }} ${{ inputs.install_packages }}
