name: "tox cache"
description: "cache the tox test environment"

inputs:
  lock_file:
    description: "conda-lock environment requirements filename"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/.tox
        key: ${{ runner.os }}-tox-${{ matrix.session }}-${{ matrix.version }}-${{ hashFiles(inputs.lock_file) }}
