name: "conda-pkg-cache"
description: "cache the conda environment packages"

inputs:
  cache_period:
    description: "conda environment cache timestamp"
    required: true
  env_name:
    description: "environment name"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/cache@v3
      with:
        path: ~/conda_pkgs_dir
        key: ${{ runner.os }}-conda-pkg-${{ inputs.env_name }}-${{ inputs.cache_period }}
