# Copyright (c) 2021, GeoVista Contributors.
#
# This file is part of GeoVista and is distributed under the 3-Clause BSD license.
# See the LICENSE file in the package root directory for licensing details.

"""Tests for the reading-time scanner and the coverage it polices.

Every page a reader reads start to finish opens with a reading-time banner. A
page that is navigated rather than read carries none, and is named in
:data:`EXEMPT` with the reason beside it. These tests hold the documentation to
that, so a page with no banner is never ambiguous between "it is exempt" and
"nobody got round to it".

The corpus is derived from the source tree rather than declared, so a page is
governed from the day it lands rather than from the day somebody remembers to
list it here. The pages are read as text and nothing here needs ``sphinx``, so
unlike the rest of ``tests/docs`` this module never skips.

"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

#: The documentation source, which is the corpus this gate is derived from.
DOCS = Path(__file__).parents[2] / "docs" / "src"

#: The trees holding no page anybody writes. This is a different thing from an
#: exemption: "EXEMPT" below is for pages somebody could have put a banner on
#: and should not.
EXCLUDED_DIRS = (
    "_autoapi_templates",  # jinja templates, and excluded by "conf.py"
    "_static",  # sphinx excludes "html_static_path" from document discovery
    "generated",  # written by sphinx-gallery
    "reference/generated",  # written by sphinx-autoapi
    "tags",  # written by sphinx-tags
)

#: The excluded trees that a documentation build writes, and so are absent from
#: a fresh clone. The rest are tracked and must be present unconditionally.
BUILT_DIRS = ("generated", "reference/generated", "tags")

#: The pages that are navigated rather than read. Each entry states why,
#: because a list of names with no reasons beside them is an escape hatch.
EXEMPT = (
    # navigated: a landing page is a card grid, a table or a toctree, and a
    # reader passes through it on the way to somewhere else
    "index.rst",  # the site landing page: a card grid and a toctree
    "developer/index.rst",  # section landing page
    "explanation/index.rst",  # quadrant landing page
    "howtos/index.rst",  # quadrant landing page
    "reference/index.rst",  # quadrant landing page
    "tutorials/index.rst",  # quadrant landing page
    "reference/cli/index.rst",  # section landing page around a "click" directive
    "reference/whatsnew/index.rst",  # an include of "latest.rst" and a toctree
    # generated body: the words are a directive's output, so a duration over
    # them would be honest and still useless
    "reference/changelog.rst",  # the body is a "changelog" directive
    "reference/cli/download.rst",  # the body is generated by "sphinx-click"
    "reference/cli/examples.rst",  # the body is generated by "sphinx-click"
    "reference/cli/plot.rst",  # the body is generated by "sphinx-click"
    "reference/whatsnew/latest.rst",  # release notes, rewritten each release
    # lookup: a table consulted for one entry, where a duration would invite a
    # reader to treat it as a chapter
    "reference/about.rst",  # package metadata, largely an included file
    "reference/bindings.rst",  # a key-binding table, one copy per platform tab
    "reference/environment.rst",  # a table of environment variables
    "reference/glossary.rst",  # a glossary, consulted rather than read in order
    # included: the body is another page, which carries the banner itself
    "developer/towncrier.rst",  # an include of "changelog.md"
)


def published_pages(docs: Path = DOCS) -> list[Path]:
    """Gather every hand-written page that sphinx publishes.

    Parameters
    ----------
    docs : Path, optional
        The documentation source root. It defaults to this repository's, which
        is what the gate reads; a test passes a tree of its own.

    Returns
    -------
    list of Path
        The ``.rst``, ``.md`` and ``.ipynb`` sources, sorted.

    """
    found: list[Path] = []

    for pattern in ("*.rst", "*.md", "*.ipynb"):
        for path in docs.rglob(pattern):
            relative = path.relative_to(docs).as_posix()

            if any(relative.startswith(f"{name}/") for name in EXCLUDED_DIRS):
                continue

            found.append(path)

    return sorted(found)


def identify(page: Path) -> str:
    """Name a page, for an exemption lookup or a parametrised test identifier.

    Parameters
    ----------
    page : Path
        The page.

    Returns
    -------
    str
        Its path relative to the documentation source root.

    """
    return page.relative_to(DOCS).as_posix()


def governed_pages() -> list[Path]:
    """Return the pages required to carry a banner."""
    return [page for page in published_pages() if identify(page) not in EXEMPT]


def exempt_pages() -> list[Path]:
    """Return the pages required to carry none."""
    return [page for page in published_pages() if identify(page) in EXEMPT]


#: A reStructuredText page in the shape the rule describes.
RST_PAGE = """\
.. _a-target:

Title
=====

.. readingtime::

Lead text.

Section
-------

Body text.
"""

#: The same page in MyST, reaching the directive through an ``eval-rst`` window
#: as both of the MyST pages in this documentation set do.
MYST_PAGE = """\
# Title

```{eval-rst}
.. readingtime::
```

Lead text.

## Section

Body text.
"""


def notebook(*cells: tuple[str, str]) -> str:
    """Build the JSON of a notebook from ``(cell_type, source)`` pairs.

    Parameters
    ----------
    *cells : tuple of (str, str)
        The type and source of each cell, in document order.

    Returns
    -------
    str
        The ``.ipynb`` JSON.

    """
    return json.dumps(
        {
            "cells": [
                {"cell_type": kind, "source": source.splitlines(keepends=True)}
                for kind, source in cells
            ]
        }
    )


def test_the_rst_title_is_the_first_underline(reading):
    """The underline, as the title itself has no column-0 marker."""
    assert reading.title_line(RST_PAGE, ".rst") == 4


def test_the_rst_first_section_is_the_second_underline(reading):
    """Everything between the two underlines is the lead."""
    assert reading.first_section_line(RST_PAGE, ".rst") == 11


def test_a_transition_is_not_an_underline(reading):
    """A rule between paragraphs underlines nothing, so it opens no section."""
    text = RST_PAGE.replace("Lead text.\n", "Lead text.\n\n----\n")

    assert reading.first_section_line(text, ".rst") == 13


def test_a_page_with_no_sections_is_all_lead(reading):
    """There is nowhere else on such a page for the banner to be."""
    text = "Only a Title\n============\n\n.. readingtime::\n\nBody.\n"

    assert reading.first_section_line(text, ".rst") is None
    assert reading.carries_reading_time(text, ".rst")


def test_a_directive_in_the_lead_satisfies_the_rule(reading):
    """Both page formats, read by different halves of the scanner."""
    assert reading.carries_reading_time(RST_PAGE, ".rst")
    assert reading.carries_reading_time(MYST_PAGE, ".md")


def test_a_page_without_the_directive_does_not(reading):
    """The gate would pass vacuously if an absent directive were found."""
    text = RST_PAGE.replace(".. readingtime::\n\n", "")

    assert not reading.carries_reading_time(text, ".rst")


def test_a_directive_below_the_lead_is_a_demonstration(reading):
    """What lets "developer/documentation.rst" show live banners.

    Its ``readingtime`` section renders two of them to show what an argument
    does to the figure. They are the page's subject rather than its banner, so
    they are found as directives and are not in the lead.
    """
    text = RST_PAGE.replace("Body text.\n", ".. readingtime:: 5\n\nBody text.\n")

    assert len(reading.directive_lines(text, ".rst")) == 2
    assert reading.lead_directive_lines(text, ".rst") == [6]


def test_an_indented_directive_does_not_count(reading):
    """Inside a literal block it is quoted rather than rendered."""
    text = RST_PAGE.replace(".. readingtime::", ".. code::\n\n       .. readingtime::")

    assert reading.directive_lines(text, ".rst") == []


def test_a_directive_glued_to_trailing_text_does_not_count(reading):
    """Docutils parses ``.. readingtime::junk`` as a comment, rendering nothing.

    A prefix match would credit the page with a banner that never appears.
    """
    text = RST_PAGE.replace(".. readingtime::", ".. readingtime::junk")

    assert reading.directive_lines(text, ".rst") == []


def test_a_native_myst_directive_is_found_although_it_is_itself_a_fence(reading):
    """A scanner that skipped each fence whole could not see the opening rail."""
    text = MYST_PAGE.replace(
        "```{eval-rst}\n.. readingtime::\n```", "```{readingtime}\n```"
    )

    assert reading.directive_lines(text, ".md") == [3]
    assert reading.carries_reading_time(text, ".md")


@pytest.mark.parametrize(
    "info",
    ["{readingtime}", "{readingtime} 30", "{readingtime} 200wpm"],
    ids=["bare", "minutes", "wpm"],
)
def test_a_native_myst_directive_carrying_an_argument_is_still_found(info, reading):
    """The name is the first token of the info string rather than the whole."""
    text = MYST_PAGE.replace("```{eval-rst}\n.. readingtime::\n```", f"```{info}\n```")

    assert reading.carries_reading_time(text, ".md")


def test_a_different_myst_directive_is_not_found(reading):
    """The token match must not widen into a substring or a prefix match."""
    text = MYST_PAGE.replace("```{eval-rst}", "```{note}")

    assert reading.directive_lines(text, ".md") == []


def test_a_directive_quoted_inside_a_plain_myst_fence_does_not_count(reading):
    """A fence with no info string is opaque, so its body renders nothing."""
    text = MYST_PAGE.replace("Body text.\n", "````\n```{readingtime}\n```\n````\n")

    assert reading.directive_lines(text, ".md") == [4]


def test_a_heading_inside_a_myst_fence_is_not_a_section(reading):
    """Otherwise a quoted heading would close the lead early."""
    text = MYST_PAGE.replace("Lead text.\n", "```\n## Not a heading\n```\n")

    assert reading.first_section_line(text, ".md") == 11


def test_the_myst_scanner_keeps_the_rail_discipline(reading):
    """A four-backtick block may quote a three-backtick one without closing."""
    text = "# Title\n\n````\n```\n## quoted\n```\n````\n\n## Real\n"

    assert reading.first_section_line(text, ".md") == 9


def test_a_notebook_is_read_through_its_markdown_cells(reading):
    """Only they carry page structure, and only they are rendered as MyST."""
    text = notebook(
        ("markdown", "# Title\n"),
        ("code", "# not a title\n"),
        ("markdown", "```{eval-rst}\n.. readingtime:: 30\n```\n"),
        ("markdown", "## Section\n"),
    )

    assert reading.title_line(text, ".ipynb") == 1
    assert reading.directive_lines(text, ".ipynb") == [4]
    assert reading.first_section_line(text, ".ipynb") == 7
    assert reading.carries_reading_time(text, ".ipynb")


def test_a_notebook_code_cell_cannot_supply_a_directive(reading):
    """A string in a code cell is output, and renders no banner."""
    text = notebook(
        ("markdown", "# Title\n"),
        ("code", '".. readingtime::"\n'),
        ("markdown", "## Section\n"),
    )

    assert not reading.carries_reading_time(text, ".ipynb")


def test_the_corpus_is_not_empty():
    """A gate that finds nothing passes by never having looked."""
    assert len(published_pages()) > 20


def test_the_corpus_holds_a_member_of_every_section_it_governs():
    """Membership rather than a count, which would need re-measuring."""
    found = {identify(page) for page in published_pages()}

    for member in (
        "index.rst",
        "developer/documentation.rst",
        "developer/changelog.md",
        "explanation/index.rst",
        "howtos/index.rst",
        "reference/glossary.rst",
        "tutorials/region-manifold-extraction.ipynb",
    ):
        assert member in found, f"{member} is missing from the corpus"


def test_the_corpus_excludes_the_generated_trees():
    """They hold hundreds of pages nobody writes and nobody reads in order."""
    found = {identify(page) for page in published_pages()}

    for name in EXCLUDED_DIRS:
        assert not any(page.startswith(f"{name}/") for page in found), (
            f"{name} is in the corpus"
        )


def test_published_pages_reads_the_tree_it_is_given(tmp_path):
    """The default argument must be a default and not the only tree it reads."""
    (tmp_path / "reference").mkdir()
    (tmp_path / "page.rst").write_text("Title\n=====\n", encoding="utf-8")
    (tmp_path / "reference" / "notes.md").write_text("# Notes\n", encoding="utf-8")
    (tmp_path / "tags").mkdir()
    (tmp_path / "tags" / "excluded.rst").write_text("Tag\n===\n", encoding="utf-8")

    found = {
        path.relative_to(tmp_path).as_posix() for path in published_pages(tmp_path)
    }

    assert found == {"page.rst", "reference/notes.md"}


@pytest.mark.parametrize("name", EXCLUDED_DIRS)
def test_every_excluded_tree_exists(name):
    """An exclusion naming nothing is an exclusion that stopped excluding.

    The name is checked whether or not the tree is present, as a leading or
    trailing slash would make the prefix match in :func:`published_pages`
    silently exclude nothing.
    """
    assert not name.startswith("/"), f"{name} has a leading slash"
    assert not name.endswith("/"), f"{name} has a trailing slash"

    if name in BUILT_DIRS and not (DOCS / name).is_dir():
        pytest.skip(f"{name} exists only after a documentation build")

    assert (DOCS / name).is_dir(), f"{name} is not a directory under {DOCS}"


def test_the_autoapi_templates_are_excluded_by_the_build_too():
    """The exclusion tracks "conf.py" rather than restating a claim about it."""
    conf = (DOCS / "conf.py").read_text(encoding="utf-8")

    assert '"_autoapi_templates"' in conf


@pytest.mark.parametrize("name", EXEMPT)
def test_every_exempt_page_still_exists(name):
    """A renamed page whose exemption stayed behind would be silently exempt."""
    assert (DOCS / name).is_file(), f"{name} is exempt but is not a page"


def test_the_exempt_pages_are_all_in_the_corpus():
    """An exemption for a page the corpus never had is exempting nothing."""
    found = {identify(page) for page in published_pages()}

    assert set(EXEMPT) <= found


def test_no_page_is_exempt_twice():
    """A duplicate is a merge that went in twice, and hides one of the reasons."""
    assert len(set(EXEMPT)) == len(EXEMPT)


@pytest.mark.parametrize("page", governed_pages(), ids=identify)
def test_every_governed_page_carries_a_reading_time(page, reading):
    """A page is read start to finish unless its entry in "EXEMPT" says why not."""
    text = page.read_text(encoding="utf-8")

    assert reading.carries_reading_time(text, page.suffix), (
        f"{identify(page)} carries no reading-time banner: put a 'readingtime' "
        f"directive at column 0 after the title and before the first section "
        f"heading, or add the page to EXEMPT with the reason it is navigated "
        f"rather than read"
    )


@pytest.mark.parametrize("page", governed_pages(), ids=identify)
def test_no_governed_page_carries_two_banners(page, reading):
    """Two banners in one lead is a copy-paste rather than a decision."""
    text = page.read_text(encoding="utf-8")

    assert len(reading.lead_directive_lines(text, page.suffix)) == 1


@pytest.mark.parametrize("page", exempt_pages(), ids=identify)
def test_no_exempt_page_carries_the_directive(page, reading):
    """Anywhere on the page, as an exempt one has no call to demonstrate it."""
    text = page.read_text(encoding="utf-8")

    assert reading.directive_lines(text, page.suffix) == [], (
        f"{identify(page)} is exempt and yet carries the directive: remove it, "
        f"or remove the page from EXEMPT"
    )
