# Reference:
#   - https://github.com/actions/checkout
#   - https://github.com/prefix-dev/setup-pixi
#   - https://github.com/pyvista/setup-headless-display-action

name: ci-docs

on:
  pull_request:

  push:
    branches:
      - "main"
      - "v*x"
      - "!pixi-auto-update"
      - "!pre-commit-ci-update-config"
      - "!dependabot/*"
    tags:
      - "v*"

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  tests:
    name: "${{ matrix.session }} (${{ matrix.version }})"
    runs-on: "${{ matrix.os }}"

    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-22.04"]
        version: ["py313"]
        session: ["doctest"]

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: "environment configure"
        env:
          # Maximum cache period (in weeks) before forcing a cache refresh.
          CACHE_WEEKS: 2
        run: |
          echo "CACHE_PERIOD=$(date +%Y).$(expr $(date +%U) / ${CACHE_WEEKS})" >> ${GITHUB_ENV}

      - uses: pyvista/setup-headless-display-action@5bc8de3bc71fcda7a96439571287a554901541a0

      - name: "setup pixi"
        uses: prefix-dev/setup-pixi@a09b6247153796b190642a2b53fac4241043cf6f
        with:
          environments: "docs-${{ matrix.version }}"
          frozen: true
          activate-environment: true

      - name: "cartopy cache"
        uses: ./.github/workflows/composite/cartopy-cache
        with:
          cache_period: ${{ env.CACHE_PERIOD }}

      - name: "geovista cache"
        uses: ./.github/workflows/composite/geovista-cache
        with:
          cache_period: ${{ env.CACHE_PERIOD }}

      - name: "${{ matrix.session }} (${{ matrix.version }})"
        run: |
          geovista --report
          xvfb-run -a pixi run --frozen make ${{ matrix.session }}
