# Reference:
#   - https://github.com/actions/checkout
#   - https://github.com/actions/labeler

name: ci-label

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -l {0}

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  triage:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/labeler@f27b608878404679385c85cfa523b85ccb86e213

      - if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' || github.event.pull_request.user.login == 'pre-commit-ci[bot]' }}
        run: |
          gh issue edit ${{ github.event.issue.number || github.event.pull_request.number }} --add-label 'skip-changelog'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - if: ${{ startsWith(github.event.pull_request.head.ref, 'breaking-change') || startsWith(github.event.pull_request.head.ref, 'breaking') || startsWith(github.event.pull_request.head.ref, 'break') }}
        run: |
          gh issue edit ${{ github.event.issue.number || github.event.pull_request.number }} --add-label 'breaking-change'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - if: ${{ startsWith(github.event.pull_request.head.ref, 'bug') || startsWith(github.event.pull_request.head.ref, 'fix') || startsWith(github.event.pull_request.head.ref, 'patch') }}
        run: |
          gh issue edit ${{ github.event.issue.number || github.event.pull_request.number }} --add-label 'type: bug'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - if: ${{ startsWith(github.event.pull_request.head.ref, 'debt') }}
        run: |
          gh issue edit ${{ github.event.issue.number || github.event.pull_request.number }} --add-label 'type: tech-debt'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - if: ${{ startsWith(github.event.pull_request.head.ref, 'doc') || startsWith(github.event.pull_request.head.ref, 'docs') }}
        run: |
          gh issue edit ${{ github.event.issue.number || github.event.pull_request.number }} --add-label 'type: documentation'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - if: ${{ startsWith(github.event.pull_request.head.ref, 'feat') || startsWith(github.event.pull_request.head.ref, 'feature') }}
        run: |
          gh issue edit ${{ github.event.issue.number || github.event.pull_request.number }} --add-label 'type: enhancement'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - if: ${{ startsWith(github.event.pull_request.head.ref, 'ex') || startsWith(github.event.pull_request.head.ref, 'example') || startsWith(github.event.pull_request.head.ref, 'examples') }}
        run: |
          gh issue edit ${{ github.event.issue.number || github.event.pull_request.number }} --add-label 'type: examples'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - if: ${{ startsWith(github.event.pull_request.head.ref, 'merge-back') || startsWith(github.event.pull_request.head.ref, 'mb') }}
        run: |
          gh issue edit ${{ github.event.issue.number || github.event.pull_request.number }} --add-label 'type: merge-back'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - if: ${{ startsWith(github.event.pull_request.head.ref, 'pixi') }}
        run: |
          gh issue edit ${{ github.event.issue.number || github.event.pull_request.number }} --add-label 'pixi'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - if: ${{ startsWith(github.event.pull_request.head.ref, 'perf') || startsWith(github.event.pull_request.head.ref, 'performance') }}
        run: |
          gh issue edit ${{ github.event.issue.number || github.event.pull_request.number }} --add-label 'type: performance'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - if: ${{ startsWith(github.event.pull_request.head.ref, 'spec') || startsWith(github.event.pull_request.head.ref, 'spec0') }}
        run: |
          gh issue edit ${{ github.event.issue.number || github.event.pull_request.number }} --add-label 'type: spec-0'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
