# Reference:
#   - https://github.com/actions/checkout
#   - https://github.com/actions/upload-artifact
#   - https://github.com/prefix-dev/setup-pixi

name: ci-tests-docs

on:
  pull_request:

  push:
    branches:
      - "main"
      - "v*x"
      - "!pixi-auto-update"
      - "!pre-commit-ci-update-config"
      - "!dependabot/*"
    tags:
      - "v*"

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  tests:
    name: "test images (${{ matrix.version }})"
    runs-on: "${{ matrix.os }}"

    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-22.04"]
        version: ["py313"]

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: "environment configure"
        env:
          # Maximum cache period (in weeks) before forcing a cache refresh.
          CACHE_WEEKS: 2
        run: |
          echo "CACHE_PERIOD=$(date +%Y).$(expr $(date +%U) / ${CACHE_WEEKS})" >> ${GITHUB_ENV}

      - name: "apt install"
        run: |
          sudo apt-get update
          sudo apt-get install libgl1 libglx-mesa0

      - name: "setup pixi"
        uses: prefix-dev/setup-pixi@1b2de7f3351f171c8b4dfeb558c639cb58ed4ec0
        with:
          environments: "geovista-${{ matrix.version }}"
          frozen: true
          activate-environment: true

      - name: "cartopy cache"
        uses: ./.github/workflows/composite/cartopy-cache
        with:
          cache_period: ${{ env.CACHE_PERIOD }}

      - name: "geovista cache"
        uses: ./.github/workflows/composite/geovista-cache
        with:
          cache_period: ${{ env.CACHE_PERIOD }}

      - name: "test images (${{ matrix.version }})"
        run: |
          geovista --report
          pixi run --frozen tests-doc

      - name: "upload test images"
        if: ${{ failure() && !cancelled() }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: ci-tests-docs-test-images-failure-${{ github.job }}-${{ strategy.job-index }}
          path: ${{ github.workspace }}/test_images_failed
